;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Aug 27 2018
; Processor: PIC16F877A
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f877a.inc                ; Include register definition file

;====================================================================
; VARIABLES
;====================================================================
Final_Value EQU 0x20

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start

;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code
Start
      ; Write your code here
    BSF     STATUS,5
    MOVLW   0XFF
    MOVWF   TRISA
    MOVLW   0
    MOVWF   TRISB
    MOVWF   TRISC
    MOVWF   ADRESL
    BCF     STATUS,5
    MOVWF   ADRESH
Loop:
    CALL    ADC_INITIALISE
    CALL    ADC_READ
    BSF     STATUS,5
    MOVF    ADRESL,W
    BCF     STATUS,5
    MOVWF   PORTB

    MOVF    ADRESH,W
    MOVWF   PORTC
    GOTO    Loop
ADC_INITIALISE:
    BSF     STATUS,5
    MOVLW   0X80
    MOVWF   ADCON1
    BCF     STATUS,5
    MOVLW   0X01
    MOVWF   ADCON0
    RETURN
ADC_READ:
    BCF     STATUS,5
    BSF     ADCON0,2
WAIT:
    BTFSC   ADCON0,2
    GOTO    WAIT
    
    RETURN

;====================================================================
      END
