;====================================================================
; Main.asm file generated by New Project wizard
; Created by  : Prabhu Ram N
; Created:   Thu Jul 5 2018
; Processor: PIC16F877A
; Compiler:  MPASM (Proteus)
;====================================================================
; DEFINITIONS
;====================================================================
#include p16f877a.inc                ; Include register definition file
;====================================================================
; VARIABLES
;====================================================================
My_reg1 equ 0x20
My_temp equ 0x21
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start

;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code
Start:
    call PORT_Init              ; Calling Sub Function as user defined
    movlw   0x00  ;First Data
    movwf   My_reg1
    movlw   0x80   ;Second Data
    addwf   My_reg1,0
    ;subwf   My_reg1,0
    ;movwf   My_temp
    btfsc   STATUS,0
    incf    My_temp
    movf    My_temp,0
    movwf   PORTB

Loop:   goto  Loop        

PORT_Init:
    bsf STATUS,5
    movlw 0x00
    movwf TRISB
    bcf STATUS,5
    return
    



;====================================================================
      END
