;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Sat Aug 4 2018
; Processor: PIC16F877A
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f877a.inc                ; Include register definition file

;====================================================================
; VARIABLES
;====================================================================
REG1 EQU 0X20
REG2 EQU 0X21

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start
    ORG 0x04
    btfsc INTCON,2
    goto timer0isr
    btfsc INTCON,1
    goto extint
    btfsc INTCON,0
    goto port_isr
    btfsc PIR1,0
    goto timer1isr
    
    org 0x0050
timer0isr:
        bsf PORTB,0
        MOVLW 0XFF
        MOVWF TMR0
        bcf INTCON,2
        retfie
extint:
    retfie
port_isr:
    retfie
timer1isr:

    BSF PORTB,1
    bcf PIR1,0
    movlw 0xff      ; TMR1H:L = 0xfffe
    movwf TMR1H
    movlw 0xfe
    ;decf  TMR1H,0
    movwf TMR1L
    retfie
        


;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code
    org 0x100
Start

    BSF STATUS,5          ; Bank 1 Selected
    ; Enable necessary bits in required Registers
    movlw 0x00
    movwf TRISB
    movwf TRISD
    BSF TRISC,0
    ;In OPTION_REG Bit positions  
    ; T0CS for clock source if 0 Internal Clock else External Clock
    ; TOSE for edge Trigger if 1 High to low transistion else low to high Transistion
    ; PSA for TIMER0 or WDT prescaler 1 to WDT 0 to TIMER0
    ; PS2:PS0 for prescaler 0:7 
    ; for External clock Counter
    CLRF OPTION_REG
    movlw 0xf1     
    movwf OPTION_REG  ; 
    BSF INTCON,5 ; TMR0IE
    BSF INTCON,7 ; Global IE
    BSF INTCON,6 ; Peripheral IE
    BSF PIE1,0   ; Timer1 IE at bank 1
    
    BCF STATUS,5
    clrf PORTB
    CLRF PORTC
    movlw 0xff
    movwf TMR0
    movlw 0xff      ; TMR1H:L = 0xfffe
    movwf TMR1H
    movlw 0xfe
    ;decf  TMR1H,0
    movwf TMR1L
    movlw 0x07   ;00000111 -> 1:1prescaler Counter last bit to ON
    movwf T1CON
    clrf PORTD
;T1ISR:btfss PIR1,0
;    BCF PORTB,1
;    goto T1ISR
;    bsf PORTB,1


Loop
    COMF PORTD
    CALL DELAY
    goto  Loop


DELAY:
    MOVLW 0XFF
    MOVWF REG1
L2: MOVWF REG2
L1: DECFSZ REG2,1
    GOTO L1
    DECFSZ REG1,1
    GOTO L2
    RETURN

;====================================================================
      END
