;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Jul 4 2018
; Processor: PIC16F877A
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f877a.inc                ; Include register definition file

;====================================================================
; VARIABLES
;====================================================================
REG1 equ 0x20
REG2 EQU 0X21
REG3 EQU 0X22
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start

;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code
Start
      BSF STATUS,5
	  MOVLW 0x00
	  MOVWF TRISB
	  
	  BCF STATUS,5
	  MOVLW 0x08       ; Digit Carry
;	  MOVLW 0x88		; Carry bit
;	  MOVLW 0X80		; Zero bit
	  MOVWF REG1
	  ADDWF REG1,0

	  ;MOVF	STATUS,0
	  MOVWF	PORTB
;	  CALL	DELAY
Loop:  
      goto  Loop
DELAY:	
		MOVLW	0X02
		MOVWF	REG2

L2:		MOVF	REG3,0
L1:		DECF	REG3
		BTFSS	STATUS,2
		GOTO	L1
		DECF	REG2
		BTFSS	STATUS,2
		GOTO 	L2
		RETURN
;====================================================================
      END
